import "../styles/globals.css";
import localFont from 'next/font/local'

const myFont = localFont({ src: '../../public/fonts/IRANSans.ttf' })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <main className={myFont.className}>{children}</main>
      </body>
    </html>
  )
}
