// app/layout.tsx
import "../styles/globals.css";
import localFont from "next/font/local";
import Head from "next/head";

const myFont = localFont({ src: "../../public/fonts/IRANSans.ttf" });

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <Head>
        <title>Boolooz</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>
        <main className={myFont.className}>
          <header className="bg-white text-center py-4 border-b border-gray-200">
            <h1 className="text-3xl font-bold text-[#FB923C]">بـــولـــوز</h1>
          </header>
          <section>{children}</section>
          {modal && (
            <div id="modal-root-id">{modal}</div>
          )}
          <footer className="text-center py-4 bg-gray-100 border-t border-gray-200">
            <p>© 2024 Boolooz. All rights reserved.</p>
          </footer>
        </main>
      </body>
    </html>
  );
}
